### ISSUE TITLE
Lis tag matches show duplicate item

### ISSUE THREAD

**Issue by erf** [kupospelov/vis-ctags#14]
If you go to `vis.c` line 1993 and char 14 and press **List tag items** i get two entries of `vis-core.h` which both lead to the same place, line 176 char 1.

Maybe there is a way to remove these duplicates?

**Comment by kupospelov** [comment]
The places are probably different, but this is not obvious since the menu only shows the file names. The issue is that we cannot distinguish between the same menu items. I think #11 should fix this, since the menu items will contain not only the file name, but also the ex command, so we would be able both to show the difference and correctly identify the user choice.

**Comment by erf** [comment]
I tried to go to both entries and i end up in the same place (btw the start char was 18 `->win`), but this will be more apparant in #11 if you show line number (and char pos) for each entry.

**Comment by erf** [comment]
I tried the new menu and now it points to two different places. Nice!
